component_depth: 1
languages:
- python
production:
  exclude:
    - /tests/.*
    - /api/databaseutils.py
    - /database/.*
    - /web/.*
test:
  exclude:
    - /api/databaseutils.py
    - /database/.*
    - /web/.*
  include:
    - /tests/.*