component_depth: 1
languages:
- name: python
  production:
    exclude:
      - /tests/.*
      - /api/databaseutils.py
      - /database/.*
      - /web/.*
  test:
    exclude:
      - /api/databaseutils.py
      - /database/.*
      - /web/.*
    include:
      - /tests/.*