version: "3.7"
services:
  database:
    build: ./database
    restart: on-failure
    image: database
    container_name: database
    env_file: env.list
  api:
    build: ./api
    restart: on-failure
    image: api
    container_name: api
    env_file: env.list
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - database
  web:
    build: ./web
    restart: on-failure
    image: web
    container_name: web
    volumes:
      - ./web:/var/www/html
    depends_on:
      - api
    ports:
      - 5080:80
