version: "3.7"

services:
  database:
    build: ./database
    restart: on-failure
    image: database
    container_name: database
  api:
    build: ./api
    restart: on-failure
    image: api
    container_name: api
    depends_on: database